const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {originalReportData}=require('../inventory-original-report');
const selection={initialDate:'2026-08-23',finalDate:'2026-08-30',initialBasis:'initial',finalBasis:'initial'};
const source=()=>({range:{from:'2026-08-23',to:'2026-08-30'},warehouses:[{id:'oper',custom_id:2},{id:'central',custom_id:1},{id:'waste',custom_id:3}],daily:[...['2026-08-23','2026-08-24','2026-08-30'].flatMap(date=>[{date,warehouse:'oper',code:'A',unit:'UN',name:'Item',opening:10,closing:8,use:2,physicalCount:true},{date,warehouse:'oper',code:'B',unit:'UN',opening:null,closing:null},{date,warehouse:'central',code:'A',unit:'UN',opening:500,closing:500}])],issues:[],assumptions:[],sourceCapturedAt:'2026-09-22T03:00:00Z'});
test('original report isolates operational warehouse and excludes unknown balances',()=>{const r=originalReportData(source(),{type:'store'},selection,'2026-08-24','2026-08-24');assert.equal(r.parsed.products.length,1);assert.equal(r.excluded[0].code,'B');assert.equal(r.physicalFinalItems,1);assert.equal(r.warehouse.id,'oper');assert.equal(r.parsed.products[0].row[3],10);});
test('original report does not count the starting physical reset twice and keeps intervening adjustments',()=>{const s=source();s.daily[0].adjustment=100;s.daily[3].adjustment=-2;const r=originalReportData(s,{type:'store'},selection,'2026-08-23','2026-08-24');const p=r.parsed.products[0];const values=r.parsed.groups.map(g=>p.row[g.metrics.find(m=>m.field==='adjustment').column]);assert.deepEqual(values,[0,-2,0]);});
test('original report rejects missing snapshots, out of coverage and invalid balance criteria',()=>{assert.throws(()=>originalReportData(null,{type:'store'},selection,'2026-08-24','2026-08-24'),/Actualiza/);assert.throws(()=>originalReportData(source(),{type:'store'},selection,'2026-08-01','2026-08-24'),/período/);assert.throws(()=>originalReportData(source(),{type:'store'},{...selection,initialBasis:'bad'},'2026-08-24','2026-08-24'),/tipo/);});
test('processing originals needs no uploaded Kardex and identifies provisional provenance',async t=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'brewit-original-report-'));const dir=path.join(root,'.integrations/toteat-api/stock/store-1');fs.mkdirSync(path.join(dir,'v1'),{recursive:true});fs.writeFileSync(path.join(dir,'current.json'),JSON.stringify({version:'v1'}));fs.writeFileSync(path.join(dir,'v1/state.json'),JSON.stringify(source()));const app=require('../server').createApp({uploadsRoot:root,enableToteatSync:false});app.locals.toteatStockSync.rebuild=()=>({...source(),masterObservedAt:'2026-09-22T03:00:00Z',includedOrders:[]});const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));t.after(async()=>{await new Promise(r=>server.close(r));fs.rmSync(root,{recursive:true,force:true});});
 const url=`http://127.0.0.1:${server.address().port}/api/inventory/process`,body={location:'store-1',source:'originals',initialInventoryDate:selection.initialDate,finalInventoryDate:selection.finalDate,initialInventoryBasis:'initial',finalInventoryBasis:'initial',movementDateFrom:'2026-08-24',movementDateTo:'2026-08-24'};
 let response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();assert.equal(response.status,200,JSON.stringify(data));assert.equal(data.provenance.mode,'originals');assert.equal(data.report.itemCount,1);assert.equal(data.report.items[0].movements['uso-consumo-estimado'],2);assert.equal(data.executiveSummary.metrics.adjustedKardexTotalCost.available,false);
 response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,source:'files'})});assert.equal(response.status,404);
});
