const test=require('node:test'),assert=require('node:assert/strict');
const {projectionInventory}=require('../projection-inventory');const {countBoundaryReport}=require('../inventory-boundaries');
const state=()=>({range:{from:'2026-08-01',to:'2026-08-30'},warehouses:[{id:'local',custom_id:2},{id:'central',custom_id:1},{id:'waste',custom_id:3}],daily:Array.from({length:30},(_,i)=>['local','central','waste'].map(warehouse=>({date:`2026-08-${String(i+1).padStart(2,'0')}`,code:'A',name:'A',unit:'UN',warehouse,opening:i===0?100:60,physicalCount:i===0||i===15,purchase:0,use:warehouse==='local'?2:0,transfer_local_in:0,transfer_local_out:0,transfer_warehouse_in:0,transfer_warehouse_out:warehouse==='central'?1:0,transformed_in:0,transformed_out:warehouse==='central'?2:0}))).flat()});
const correction=(code,unit,from,to)=>(Date.parse(to)-Date.parse(from))/86400000+1; // +2 compensation minus 1 internal each day.
test('projection balance equals consolidated closing with the same corrections and physical resets',()=>{const s=state(),l={type:'store'};const p=projectionInventory(s,l,'2026-08-30',correction),r=countBoundaryReport(s,l,'2026-08-01','2026-08-31',correction);assert.equal(p.items[0].currentInventory,r.items[0].theoreticalFinal+30);assert.equal(p.items[0].currentInventory,45);assert.equal(p.items[0].consumption30,30);assert.equal(p.days,30);});
test('central demand includes outgoing transformations and transfers once and excludes waste warehouse',()=>{const p=projectionInventory(state(),{type:'warehouse'},'2026-08-30');assert.equal(p.items.length,1);assert.equal(p.items[0].consumption30,90);assert.equal(p.items[0].transformationOut,60);assert.equal(p.items[0].transferOut,30);assert.equal(p.items[0].currentInventory,15);});
test('unknown and incomplete stock never become zero stock purchase suggestions',()=>{const s=state();s.daily=s.daily.filter(r=>r.date!=='2026-08-10');const p=projectionInventory(s,{type:'store'},'2026-08-30');assert.equal(p.items.length,1);assert.equal(p.items[0].consumptionDays,15);assert.ok(p.warnings.some(w=>w.includes('historial parcial')));s.daily=[];assert.equal(projectionInventory(s,{type:'store'},'2026-08-30').items.length,0);});
test('partial source periods expose the actual denominator, stale dates and coverage',()=>{const s=state();s.range.to='2026-08-20';s.daily=s.daily.filter(r=>r.date<=s.range.to);const p=projectionInventory(s,{type:'store'},'2026-08-30');assert.equal(p.days,20);assert.ok(p.warnings.some(w=>w.includes('20 días')));assert.equal(p.to,'2026-08-20');});

test('findings can request a custom audit period while retaining the same corrected closing balance',()=>{const s=state(),location={type:'store'};const short=projectionInventory(s,location,'2026-08-30',correction,'2026-08-24');const full=projectionInventory(s,location,'2026-08-30',correction);assert.equal(short.days,7);assert.equal(short.items[0].consumption30,7);assert.equal(short.items[0].currentInventory,full.items[0].currentInventory);assert.equal(short.items[0].consumptionFrom,'2026-08-24');assert.equal(short.warnings.length,0);});
