const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const XLSX = require('xlsx');
const { chromium } = require('playwright-core');
const { createApp } = require('../server');
const { buildMasterReport } = require('../purchase-master-report');
const chrome = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
test('master report opens with view dates, shows optional received products and downloads matching workbook and printable PDF', { skip: !fs.existsSync(chrome) }, async t => {
  const uploadsRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'brewit-master-ui-'));
  const server = createApp({ enableLegacyTools: true, uploadsRoot }).listen(0, '127.0.0.1');
  await new Promise((resolve, reject) => { server.once('listening', resolve); server.once('error', reject); });
  const browser = await chromium.launch({ executablePath: chrome, headless: true });
  t.after(async () => { await browser.close(); server.closeAllConnections(); await new Promise(resolve => server.close(resolve)); fs.rmSync(uploadsRoot, { recursive: true, force: true }); });
  const page = await browser.newPage();
  await page.route('**/api/purchase-master-report?*', route => {
    const query = new URL(route.request().url()).searchParams;
    assert.equal(query.get('dateFrom'), '2026-09-01'); assert.equal(query.get('dateTo'), '2026-09-28');
    return route.fulfill({ json: buildMasterReport([{ scope: { location: 'store-1', label: 'Café A', type: 'store' }, rows: [{ supplierKey: '1', supplier: 'Proveedor A', document: '123', documentType: 'Factura Normal', date: '2026-09-23', totalAmount: 100, reportNet: 100, reportGross: 119, product: 'Café recibido', receivedQuantity: 2, receivedUnit: 'KG' }] }], { from: '2026-09-01', to: '2026-09-28' }, query.get('includeProducts') === 'true') });
  });
  await page.goto(`http://127.0.0.1:${server.address().port}`);
  await page.locator('[data-view=purchases]').click();
  await page.waitForFunction(() => !document.getElementById('refresh-purchases').disabled);
  const expectedFrom = await page.evaluate(() => {
    const date = new Date(`${browserIsoToday()}T12:00:00Z`); date.setUTCDate(date.getUTCDate() - 7); return date.toISOString().slice(0, 10);
  });
  assert.equal(await page.locator('#purchases-date-from').inputValue(), expectedFrom);
  await page.evaluate(() => {
    document.getElementById('purchases-date-from').value = '2026-09-01';
    document.getElementById('purchases-date-to').value = '2026-09-28';
    document.getElementById('open-purchase-master').click();
  });
  await page.waitForFunction(() => document.getElementById('purchase-master-status').textContent === 'Reporte generado.');
  assert.match(await page.locator('#purchase-master-results').innerText(), /Resumen general por proveedor y localidad/);
  assert.deepEqual(await page.locator('.master-documents thead th').allTextContents(), ['Fecha emisión', 'Tipo documento', 'Documento', 'Importe Neto']);
  assert.equal(await page.locator('.master-overview > div').count(), 4);
  assert.equal(await page.locator('.master-summary .master-grand-total').count(), 1);
  assert.doesNotMatch(await page.locator('#purchase-master-results').innerText(), /Café recibido/);
  await page.locator('#purchase-master-form input[type=checkbox]').check();
  assert.equal(await page.locator('#export-purchase-master').isDisabled(), true);
  await page.getByRole('button', { name: 'Generar reporte', exact: true }).click();
  await page.getByText('Café recibido', { exact: true }).waitFor();
  const downloadPromise = page.waitForEvent('download');
  await page.locator('#export-purchase-master').click();
  const download = await downloadPromise;
  assert.match(download.suggestedFilename(), /reporte-maestro-compras.*xlsx/);
  const workbook = XLSX.readFile(await download.path());
  const rows = XLSX.utils.sheet_to_json(workbook.Sheets['Reporte maestro'], { header: 1 });
  assert(rows.some(row => row.includes('Café recibido') && row.includes(2)));
  assert(rows.some(row => row[0] === 'Total general' && row.includes(100) && !row.includes(119)));
  await page.evaluate(() => { window.print = () => { window.masterPrintActive = document.body.classList.contains('printing-purchase-master'); }; });
  await page.locator('#print-purchase-master').click();
  assert.equal(await page.evaluate(() => window.masterPrintActive), true);
  await page.evaluate(() => document.body.classList.add('printing-purchase-master'));
  await page.emulateMedia({ media: 'print' });
  assert.equal(await page.locator('#purchase-master-form').isVisible(), false);
  assert.equal(await page.locator('#purchase-master-results').isVisible(), true);
  const pdf = await page.pdf(); assert(pdf.length > 1000);
});
