const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { chromium } = require('playwright-core');
const { createApp } = require('../server');
const CHROME_PATH = ['/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', chromium.executablePath()].find(p => fs.existsSync(p));

test('clusters: controles, persistencia, cálculo, comparación y pedidos completos', { skip: !CHROME_PATH }, async t => {
  const uploadsRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'brewit-clusters-ui-'));
  const app = createApp({ uploadsRoot, enableLegacyTools: true, reportToday: '2026-09-17' });
  const server = app.listen(0, '127.0.0.1'); await new Promise(r => server.once('listening', r));
  const base = `http://127.0.0.1:${server.address().port}`;
  const browser = await chromium.launch({ executablePath: CHROME_PATH, headless: true });
  t.after(async () => { await browser.close(); app.locals.salesClusterJobs.dispose(); await new Promise(r => server.close(r)); fs.rmSync(uploadsRoot, { recursive: true, force: true }); });
  const page = await browser.newPage({ viewport: { width: 1280, height: 900 } }), errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(base); await page.getByRole('link', { name: 'Análisis de la Venta' }).click();
  await page.waitForFunction(() => document.getElementById('demand-status').textContent.includes('Análisis actualizado.'));
  const advancedBounds = await page.locator('#demand-analysis-workspace-tab-advanced').boundingBox();
  const clustersBounds = await page.locator('#sales-clusters-open').boundingBox();
  assert.ok(clustersBounds.x >= advancedBounds.x + advancedBounds.width);
  assert.ok(Math.abs(clustersBounds.y + clustersBounds.height / 2 - advancedBounds.y - advancedBounds.height / 2) < 2);
  assert.equal(await page.locator('#demand-analysis-workspace-panel-advanced').isVisible(), false);
  await page.locator('#sales-clusters-open').click();
  await page.waitForFunction(() => document.getElementById('sales-clusters-parameter-dimensionCoverage'));
  assert.equal(await page.locator('#sales-clusters-dialog').isVisible(), true);
  assert.equal(await page.locator('#sales-clusters-parameter-dimensionCoverage').inputValue(), '50');
  assert.equal(await page.locator('#sales-clusters-dimension-gender').isDisabled(), true);
  await page.locator('#sales-clusters-minimum-coverage-gender').fill('48');
  await page.locator('#sales-clusters-minimum-coverage-gender').blur();
  assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('brewit.salesClusters.preferences.v1')).dimensions.gender.minimumCoverage), 48);
  assert.equal(await page.locator('#sales-clusters-minimum-coverage-mode').inputValue(), '');
  assert.equal(await page.locator('#sales-clusters-from').inputValue(), '2026-09-01');
  await page.locator('#sales-clusters-quality > summary').click();
  await page.locator('#sales-clusters-parameter-dimensionCoverage').fill('35'); await page.locator('#sales-clusters-parameter-dimensionCoverage').blur();
  assert.equal(await page.locator('#sales-clusters-custom').isVisible(), true);
  assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('brewit.salesClusters.preferences.v1')).parameters.dimensionCoverage), 35);
  await page.locator('#sales-clusters-reset').click();
  await page.waitForFunction(() => document.getElementById('sales-clusters-status').textContent === 'Cobertura actualizada.');
  assert.equal(await page.locator('#sales-clusters-parameter-dimensionCoverage').inputValue(), '50');
  assert.equal(await page.locator('#sales-clusters-minimum-coverage-gender').inputValue(), '');
  await page.locator('#sales-clusters-calculate').click();
  await page.waitForFunction(() => !document.getElementById('sales-clusters-results').hidden);
  assert.match(await page.locator('#sales-clusters-results').innerText(), /No hay dimensiones.*variación/);
  // Load sales through the existing upload process, without invoking TotEat.
  const rows = [['ID de orden', 'Fecha de creacion', 'Hora de creacion', 'Pago total', 'Descuentos', 'ID Producto', 'Nombre', 'Cantidad', 'Precio Lista', 'Precio a Pagar', 'Descuento', 'Categorías de Productos/Platos', 'AB.']];
  for (let i = 0; i < 40; i++) {
    const amount = i % 2 ? 4760 : 1190;
    rows.push([`ui-${i}`, `2026-09-${String(1 + Math.floor(i / 2) % 10).padStart(2, '0')}`, i % 2 ? '18:00:00' : '09:00:00', amount, 0, i % 2 ? 'B' : 'A', i % 2 ? 'Almuerzo' : 'Café', 1, amount, amount, 0, 'Venta', i % 2 ? 'FOOD.1' : 'DRINK.1']);
  }
  const form = new FormData(); form.append('sales', new Blob([rows.map(r => r.join('\t')).join('\n')]), 'ventas-clusters-ui.csv');
  const inspection = await fetch(`${base}/api/uploads/transactions/inspect?location=store-1`, { method: 'POST', body: form }).then(r => r.json());
  const confirmed = await fetch(`${base}/api/uploads/transactions/confirm`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ token: inspection.token, dateFrom: inspection.detectedRange.from, dateTo: inspection.detectedRange.to, confirmed: true, categoryConfirmed: true }) });
  assert.equal(confirmed.status, 200);
  await page.locator('#sales-clusters-parameter-minimumOrders').fill('20');
  await page.locator('#sales-clusters-parameter-minimumClusterOrders').fill('5');
  await page.locator('#sales-clusters-dimension-hour').uncheck();
  await page.locator('#sales-clusters-minimum-coverage-mode').fill('90');
  await page.locator('#sales-clusters-coverage-button').click();
  await page.waitForFunction(() => document.getElementById('sales-clusters-status').textContent === 'Cobertura actualizada.');
  const requestPromise = page.waitForRequest(r => r.url().endsWith('/api/sales-clusters/jobs') && r.method() === 'POST');
  await page.locator('#sales-clusters-calculate').click(); const request = await requestPromise;
  assert.equal(request.postDataJSON().dimensions.hour.enabled, false);
  assert.equal(request.postDataJSON().dimensions.mode.minimumCoverage, 90);
  await page.waitForFunction(() => document.querySelectorAll('.sales-clusters-card').length > 0 && document.getElementById('sales-clusters-cancel').hidden);
  assert.match(await page.locator('#sales-clusters-results').innerText(), /40/);
  await page.locator('.sales-clusters-card').first().getByRole('button', { name: 'Ver detalle y pedidos' }).click();
  await page.waitForFunction(() => document.getElementById('sales-clusters-detail').textContent.includes('Página 1'));
  assert.match(await page.locator('#sales-clusters-detail').innerText(), /Abrir pedido/);
  const originalCards = await page.locator('.sales-clusters-card').count();
  await page.locator('.sales-clusters-card').first().getByRole('button', { name: 'Profundizar', exact: true }).click();
  await page.waitForFunction(() => document.getElementById('sales-clusters-coverage').textContent.includes('Cobertura del grupo seleccionado'));
  await page.locator('#sales-clusters-parameter-minimumOrders').fill('100');
  await page.locator('#sales-clusters-calculate').click();
  await page.waitForFunction(() => document.getElementById('sales-clusters-detail').textContent.includes('No fue posible subdividir'));
  assert.equal(await page.locator('.sales-clusters-card').count(), originalCards);
  await page.locator('#sales-clusters-context').getByRole('button', { name: 'Volver al resultado padre' }).click();
  await page.waitForFunction(() => document.getElementById('sales-clusters-parameter-minimumOrders').value === '20');
  await page.locator('#sales-clusters-config-name').fill('Ventas de prueba'); await page.locator('#sales-clusters-save').click();
  assert.equal(await page.locator('#sales-clusters-saved option').count(), 2);
  await page.locator('#sales-clusters-results').getByRole('button', { name: 'Comparar otro período con estos grupos' }).click();
  const compareRequest = page.waitForRequest(r => r.url().endsWith('/api/sales-clusters/jobs') && r.method() === 'POST');
  await page.locator('#sales-clusters-calculate').click(); assert.ok((await compareRequest).postDataJSON().referenceJobId);
  await page.waitForFunction(() => document.getElementById('sales-clusters-results').textContent.includes('Cambio (puntos)'));
  await page.locator('#sales-clusters-context').getByRole('button', { name: 'Volver al descubrimiento de clusters' }).click();
  await page.locator('#sales-clusters-close').click();
  assert.deepEqual(errors, []);
});
