const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs'), os = require('node:os'), path = require('node:path');
const { chromium } = require('playwright-core');
const { createApp } = require('../server');
const chrome = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
test('weekly tab follows statement and uses selected filters with five weeks and a total', { skip: !fs.existsSync(chrome) }, async t => {
  const uploadsRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'brewit-weekly-ui-'));
  const server = createApp({ enableLegacyTools: true, uploadsRoot, reportToday: '2026-09-28' }).listen(0, '127.0.0.1');
  await new Promise((resolve, reject) => { server.once('listening', resolve); server.once('error', reject); });
  const browser = await chromium.launch({ executablePath: chrome, headless: true });
  t.after(async () => { await browser.close(); server.closeAllConnections(); await new Promise(resolve => server.close(resolve)); fs.rmSync(uploadsRoot, { recursive: true, force: true }); });
  const page = await browser.newPage();
  await page.goto(`http://127.0.0.1:${server.address().port}`);
  await page.locator('[data-view="financial-results"]').click();
  await page.waitForFunction(() => !document.querySelector('#financial-results-filters button[type=submit]').disabled);
  await page.locator('#financial-results-period').selectOption('custom');
  await page.locator('#financial-results-from').fill('2026-09-01');
  await page.locator('#financial-results-to').fill('2026-09-28');
  await page.locator('#financial-results-location').selectOption('store-1');
  let requests = 0;
  page.on('request', request => { if (request.url().includes('/financial-results/weekly/stream?')) requests++; });
  await page.getByRole('tab', { name: 'Resultados Semanales', exact: true }).click();
  assert.equal(requests, 0);
  assert.equal(await page.locator('#financial-weekly-month, #financial-weekly-mode').count(), 0);
  const request = page.waitForRequest(r => r.url().includes('/financial-results/weekly/stream?'));
  await page.getByRole('button', { name: 'Procesar vista', exact: true }).click();
  const url = new URL((await request).url());
  assert.equal(url.searchParams.get('location'), 'store-1');
  assert.equal(url.searchParams.has('month'), false);
  assert.equal(url.searchParams.has('weekMode'), false);
  await page.waitForFunction(() => document.getElementById('financial-weekly-status').textContent === 'Resultados semanales actualizados.');
  assert.equal(await page.locator('#financial-weekly-progress').getAttribute('value'), '100');
  assert.equal(await page.getByRole('button', { name: 'Procesar vista', exact: true }).isEnabled(), true);
  assert.match(await page.locator('.financial-weekly-table thead').innerText(), /4 oct/);
  assert.equal(await page.locator('.financial-weekly-table thead th').count(), 7);
  assert.equal(await page.locator('.financial-weekly-table tbody tr').count(), 9);
  assert.doesNotMatch(await page.locator('.financial-weekly-table').innerText(), /N\/D/);
  assert.doesNotMatch(await page.locator('.financial-weekly-table').innerText(), /parcial/);
  const percentages = await page.locator('.weekly-percent').allTextContents();
  assert.ok(percentages.every(value => /^-?[\d.]+,\d%$/.test(value)));
  const percentSizes = await page.locator('.financial-weekly-table tbody').evaluate(body => [...body.rows].map(row => {
    const cell = row.cells[1];
    return parseFloat(getComputedStyle(cell.querySelector('.weekly-percent')).fontSize) - parseFloat(getComputedStyle(cell.querySelector('.weekly-amount')).fontSize);
  }));
  assert.ok(percentSizes.every(difference => difference === 2));
  const sizes = await page.locator('.financial-weekly-table tbody').evaluate(body => [...body.rows].slice(0, 2).map(row => parseFloat(getComputedStyle(row.cells[1]).fontSize)));
  assert.equal(sizes[0] - sizes[1], 3);
  assert.match(await page.locator('.financial-weekly-table').innerText(), /Otros Consumibles/);
  assert.equal(await page.locator('#financial-results-workspace-panel-statement').isVisible(), false);
  const labels = await page.locator('#financial-results-workspace [role=tab]').allTextContents();
  assert.deepEqual(labels.slice(0, 2), ['Estado de resultados', 'Resultados Semanales']);
});
